ass4: circle.o digraph.o program.o

	g++ circle.o digraph.o program.o   -o ass8

circle.o: circle.cpp

			g++ -c -std=c++11 circle.cpp
digraph.o: digraph.cpp

	g++ -c -std=c++11 digraph.cpp

program.o: program.cpp

	g++ -c -std=c++11 program.cpp
