ass4: ShoppingCart.o LinkedList.o ItemToPurchase.o main.o

	g++ ShoppingCart.o LinkedList.o ItemToPurchase.o main.o -o ass4

main.o: main.cpp

	g++ -c -std=c++11 main.cpp

ShoppingCart.o: ShoppingCart.cpp

	g++ -c -std=c++11 ShoppingCart.cpp


ItemToPurchase.o: ItemToPurchase.cpp

	g++ -c -std=c++11 ItemToPurchase.cpp



LinkedList.o: LinkedList.cpp

	g++ -c -std=c++11 LinkedList.cpp


