lab4: testLList.o LinkedList.o

	g++ testLList.o LinkedList.o -o lab4


testLList.o: testLList.cpp

	g++ -c -std=c++11 testLList.cpp


LinkedList.o: LinkedList.cpp

	g++ -c -std=c++11 LinkedList.cpp


